### ISSUE TITLE
is it atomic?

### ISSUE THREAD

**Issue by bpceee** [beeplove/mongoose-find-one-or-create#1]
if I do double same findOneOrCreate consecutively, this will create two different document in the mongodb, 
else if i call findOneOrCreate, wait a while, then call the same findOneOrCreate again, it get the same document
this is wired...

```
var PersonSchema = mongoose.Schema({
    name: String,
    age: Number
});
PersonSchema.plugin(findOneOrCreate);
var Person = mongoose.model('Person', PersonSchema);
Person.findOneOrCreate({name: 'Mohammad'}, {name: 'Mohammad', age: 20}, function(err, person) {
    // {name: 'Mohammad', age: 20}
    console.log(person);
});
Person.findOneOrCreate({name: 'Mohammad'}, {name: 'Mohammad', age: 20}, function(err, person) {
    // {name: 'Mohammad', age: 20}
    console.log(person);
});
```

**Comment by beeplove** [comment]
findOneOrCreate creates document and return it if doesn't exist which happen in your first scenario,
otherwise, it returns the document (in you second scenario).
